import { Canvas } from "@react-three/fiber";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Suspense } from "react";
import Logo from "../components/logo";
import styles from "../styles/Home.module.css";
import {
  Bounds,
  useBounds,
  OrbitControls,
  ContactShadows,
  useGLTF,
} from "@react-three/drei";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Canvas>
          <OrbitControls makeDefault />
          <ambientLight intensity={1} />
          <spotLight
            intensity={0.5}
            angle={0.1}
            penumbra={1}
            position={[10, 15, 10]}
            castShadow
          />
          <Suspense fallback={null}>
            <Logo />
          </Suspense>
        </Canvas>
      </main>
    </div>
  );
};

export default Home;
